services:
  ibkr:
    build:
      context: ./app
      args:
        ibc_version: 3.12.0
    ports:
      - 5900:5900
    restart: unless-stopped
    volumes:
      - ./config.ini:/root/ibc/config.ini
    environment:
      - TZ=Europe/Zurich
      - TWS_MAJOR_VRSN=1012

